### ISSUE TITLE
What is the purpose of the is addon?

### ISSUE THREAD

**Issue by MrTango** [collective/collective.dms.mailcontent#2]
Could you please add some more infos to the readme, which explains a bit what this addon does.
It would make it much easier to know if people want to use, extend and/or contribute to it, rather than developing something similar ;).

For example i anderstand that it holding email as DX content types, does it also handling the fetch via IMAP or somthing like that?

**Comment by sgeulette** [comment]
Hi MrTango,

I have completed a little bit the readme file. 
This product is part of a bundle collective.dms.* providing base classes to handle a document management system. 
Mail corresponds to post mail documents but also email documents. 
We are working on other new products to handle emails from an imap box:
* https://github.com/IMIO/imio.email.dms
* https://github.com/IMIO/imio.email.parser

Regards
